### ISSUE TITLE
`Unauthorized` exception on most requests due to header requirement

### ISSUE THREAD

**Issue by karlsbjorn** [Adalyia/aiowowapi#1]
Blizzard has recently started requiring the access token to be in the request header instead of the params, so most (all?) requests throw a 401 now.

Thread on the Blizzard forums: https://us.forums.blizzard.com/en/blizzard/t/upcoming-changes-to-battlenet%E2%80%99s-api-gateway/51561
Docs for this are here, under the `API request format` section: https://develop.battle.net/documentation/guides/using-oauth/authorization-code-flow.

An easy fix is to just add a header dict in `API.get_resource` formatted as `{"Authorization": f"Bearer {access_token)}"}`

**Comment by mty22** [comment]
@karlsbjorn I fixed this one up in https://github.com/Adalyia/aiowowapi/pull/2/files#diff-ca313221fca3a81811ce44e2f6b0397deb853a3816cb022d357d964707a62c2c

You can temporarily work around this issue by:

```
# Remove the existing pip module.
pip uninstall aiowowapi

# Pick one of the two.
git clone https://github.com/Adalyia/aiowowapi.git
git clone git@github.com:Adalyia/aiowowapi.git

# Copy src/aiowowapi to your project (where ever you are importing from).
```

Once the [PR](https://github.com/Adalyia/aiowowapi/pull/2) is merged or someone else with a bit more time fixes this up, then be sure to re-install the pip module and remove the local copy from your project.

BattleTag: `frzn#1856`
Discord: `frzn_`

**Comment by Adalyia** [comment]
I just wanted to say thank you for bringing this to my attention, I don't regularly develop things for WoW anymore or play the game myself so please let me know of any problems or suggestions.
